### ISSUE TITLE
Supports for <script setup> and <style> variable injection

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#1248]
eslint-plugin-vue should be change to support [<script setup>] and [<style> variable injection].
I will list the work needed to support these on this issue.

These features were released as experimental features in Vue.js 3.0. 
So I think that the inclusion or not of the changes listed here will not affect the release of eslint-plugin-vue 7.0.0.

---

### Core 

- [x] Change the parser to parse multiple <script> blocks. (issue https://github.com/mysticatea/vue-eslint-parser/issues/78)
- ~~Change the parser to parse `<style vars="...">`. (issue https://github.com/mysticatea/vue-eslint-parser/issues/78)~~
- ~~Change the parser to parse `<script setup="...">`. (issue https://github.com/mysticatea/vue-eslint-parser/issues/78)~~
- more

### Rules

- [x] #1560 ~~Add `no-refer-vars-script-setup-define-props` rule that disallows referencing variables in `defineProps()` of `<script setup>`~~.
- [x] #1561 ~~Add `no-refer-vars-script-setup-define-emit` rule that disallows referencing variables in `defineEmit()` of `<script setup>`~~.
- [x] #1559 Add `no-export-in-script-setup` rule that disallows ES export in `<script setup>`.
- ~~Change `no-parsing-error` rule to reports parsing errors in `<script setup="...">`~~.
- ~~Change `no-parsing-error` rule to reports parsing errors in `<style vars="...">`~~.
- ~~Add `valid-script-setup` rule that checks whether `<script setup="...">` is valid arguments.~~
- ~~Add `valid-style-vars` rule that checks whether `<style vars="...">` is valid expression.~~
- ~~Add `no-vars-setup-export-default` rule that disallows referencing variables in `export default` of `<script setup>`.~~
- more

---

https://github.com/vuejs/rfcs/pull/227
https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md
https://github.com/vuejs/rfcs/pull/231
https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md

~~https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md~~
~~https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md~~

[<script setup>]: https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md
[<style> variable injection]: https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md

**Comment by ux-engineer** [comment]
I can see you've added this new rule `vue/experimental-script-setup-vars` in [pull 1303](https://github.com/vuejs/eslint-plugin-vue/pull/1303/files). Do you still need to implement the logic for this rule?

**Comment by ux-engineer** [comment]
I'm getting error `Definition for rule 'vue/experimental-script-setup-vars' was not found.In package-lock.json it can see the installed version for this package to be. 7.0.0-beta.3

@ota-meshi is there a way to install the newest beta.4 where this rule was added, by using Vue CLI, or do I need to await for some CLI plugins to be updated?

**Comment by steffchep** [comment]
I have the same issue, still using vue2, too

**Comment by ota-meshi** [comment]
Please open a new issue.

**Comment by mellester** [comment]
![image](https://user-images.githubusercontent.com/609138/122051043-70954380-cde4-11eb-8841-937eaf51f716.png)

not sure if this is they correct issues to comment on if I should move this to a separate issue.

My problem is I have a `<script setup async>` block and I get parsing erros if I use the 'await' keyword

**Comment by ota-meshi** [comment]
As you can see from the fact that this issue has not been resolved, eslint-plugin-vue does not yet support `<script setup>`.

**Comment by yyx990803** [comment]
[The RFC has been finalized](https://github.com/vuejs/rfcs/pull/227#issuecomment-872613254) and we should start working on this!

**Comment by ota-meshi** [comment]
I started working on it 😉

**Comment by ota-meshi** [comment]
As far as I know, I think I have done the work needed to support `<script setup>`. Also, regarding `<style> variable injection`, I don't think there is any work required for` eslint-plugin-vue` in the new RFC. So I will close this issue.

If you have any issues related to these, and new rule suggestions, please open a new issue.
